// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package repository_creation_template

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.RepositoryNamePrefix, b.ko.Spec.RepositoryNamePrefix) {
		delta.Add("Spec.RepositoryNamePrefix", a.ko.Spec.RepositoryNamePrefix, b.ko.Spec.RepositoryNamePrefix)
	} else if a.ko.Spec.RepositoryNamePrefix != nil && b.ko.Spec.RepositoryNamePrefix != nil {
		if *a.ko.Spec.RepositoryNamePrefix != *b.ko.Spec.RepositoryNamePrefix {
			delta.Add("Spec.RepositoryNamePrefix", a.ko.Spec.RepositoryNamePrefix, b.ko.Spec.RepositoryNamePrefix)
		}
	}

	if !reflect.DeepEqual(a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration) {
		delta.Add("Spec.EncryptionConfiguration", a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration)
	}

	if !reflect.DeepEqual(a.ko.Spec.ImageTagMutability, b.ko.Spec.ImageTagMutability) {
		delta.Add("Spec.ImageTagMutability", a.ko.Spec.ImageTagMutability, b.ko.Spec.ImageTagMutability)
	}

	if !reflect.DeepEqual(a.ko.Spec.ImageScanningConfiguration, b.ko.Spec.ImageScanningConfiguration) {
		delta.Add("Spec.ImageScanningConfiguration", a.ko.Spec.ImageScanningConfiguration, b.ko.Spec.ImageScanningConfiguration)
	}

	if !reflect.DeepEqual(a.ko.Spec.ResourceTags, b.ko.Spec.ResourceTags) {
		delta.Add("Spec.ResourceTags", a.ko.Spec.ResourceTags, b.ko.Spec.ResourceTags)
	}

	if !reflect.DeepEqual(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	}

	return delta
}

// customPreCompare ensures that both supplied Resources are treated as "equal"
// if they represent the same object but one or the other contains
// subset of fields.
func customPreCompare(
	delta *ackcompare.Delta,
	a *resource,
	b *resource,
) {
	// No custom pre-compare logic needed for RepositoryCreationTemplate
}
