// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package repository_creation_template

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.AppliedFor) != len(b.ko.Spec.AppliedFor) {
		delta.Add("Spec.AppliedFor", a.ko.Spec.AppliedFor, b.ko.Spec.AppliedFor)
	} else if len(a.ko.Spec.AppliedFor) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.AppliedFor, b.ko.Spec.AppliedFor) {
			delta.Add("Spec.AppliedFor", a.ko.Spec.AppliedFor, b.ko.Spec.AppliedFor)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CustomRoleARN, b.ko.Spec.CustomRoleARN) {
		delta.Add("Spec.CustomRoleARN", a.ko.Spec.CustomRoleARN, b.ko.Spec.CustomRoleARN)
	} else if a.ko.Spec.CustomRoleARN != nil && b.ko.Spec.CustomRoleARN != nil {
		if *a.ko.Spec.CustomRoleARN != *b.ko.Spec.CustomRoleARN {
			delta.Add("Spec.CustomRoleARN", a.ko.Spec.CustomRoleARN, b.ko.Spec.CustomRoleARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.CustomRoleRef, b.ko.Spec.CustomRoleRef) {
		delta.Add("Spec.CustomRoleRef", a.ko.Spec.CustomRoleRef, b.ko.Spec.CustomRoleRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration) {
		delta.Add("Spec.EncryptionConfiguration", a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration)
	} else if a.ko.Spec.EncryptionConfiguration != nil && b.ko.Spec.EncryptionConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration.EncryptionType, b.ko.Spec.EncryptionConfiguration.EncryptionType) {
			delta.Add("Spec.EncryptionConfiguration.EncryptionType", a.ko.Spec.EncryptionConfiguration.EncryptionType, b.ko.Spec.EncryptionConfiguration.EncryptionType)
		} else if a.ko.Spec.EncryptionConfiguration.EncryptionType != nil && b.ko.Spec.EncryptionConfiguration.EncryptionType != nil {
			if *a.ko.Spec.EncryptionConfiguration.EncryptionType != *b.ko.Spec.EncryptionConfiguration.EncryptionType {
				delta.Add("Spec.EncryptionConfiguration.EncryptionType", a.ko.Spec.EncryptionConfiguration.EncryptionType, b.ko.Spec.EncryptionConfiguration.EncryptionType)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration.KMSKey, b.ko.Spec.EncryptionConfiguration.KMSKey) {
			delta.Add("Spec.EncryptionConfiguration.KMSKey", a.ko.Spec.EncryptionConfiguration.KMSKey, b.ko.Spec.EncryptionConfiguration.KMSKey)
		} else if a.ko.Spec.EncryptionConfiguration.KMSKey != nil && b.ko.Spec.EncryptionConfiguration.KMSKey != nil {
			if *a.ko.Spec.EncryptionConfiguration.KMSKey != *b.ko.Spec.EncryptionConfiguration.KMSKey {
				delta.Add("Spec.EncryptionConfiguration.KMSKey", a.ko.Spec.EncryptionConfiguration.KMSKey, b.ko.Spec.EncryptionConfiguration.KMSKey)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ImageTagMutability, b.ko.Spec.ImageTagMutability) {
		delta.Add("Spec.ImageTagMutability", a.ko.Spec.ImageTagMutability, b.ko.Spec.ImageTagMutability)
	} else if a.ko.Spec.ImageTagMutability != nil && b.ko.Spec.ImageTagMutability != nil {
		if *a.ko.Spec.ImageTagMutability != *b.ko.Spec.ImageTagMutability {
			delta.Add("Spec.ImageTagMutability", a.ko.Spec.ImageTagMutability, b.ko.Spec.ImageTagMutability)
		}
	}
	if len(a.ko.Spec.ImageTagMutabilityExclusionFilters) != len(b.ko.Spec.ImageTagMutabilityExclusionFilters) {
		delta.Add("Spec.ImageTagMutabilityExclusionFilters", a.ko.Spec.ImageTagMutabilityExclusionFilters, b.ko.Spec.ImageTagMutabilityExclusionFilters)
	} else if len(a.ko.Spec.ImageTagMutabilityExclusionFilters) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ImageTagMutabilityExclusionFilters, b.ko.Spec.ImageTagMutabilityExclusionFilters) {
			delta.Add("Spec.ImageTagMutabilityExclusionFilters", a.ko.Spec.ImageTagMutabilityExclusionFilters, b.ko.Spec.ImageTagMutabilityExclusionFilters)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LifecyclePolicy, b.ko.Spec.LifecyclePolicy) {
		delta.Add("Spec.LifecyclePolicy", a.ko.Spec.LifecyclePolicy, b.ko.Spec.LifecyclePolicy)
	} else if a.ko.Spec.LifecyclePolicy != nil && b.ko.Spec.LifecyclePolicy != nil {
		if *a.ko.Spec.LifecyclePolicy != *b.ko.Spec.LifecyclePolicy {
			delta.Add("Spec.LifecyclePolicy", a.ko.Spec.LifecyclePolicy, b.ko.Spec.LifecyclePolicy)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Prefix, b.ko.Spec.Prefix) {
		delta.Add("Spec.Prefix", a.ko.Spec.Prefix, b.ko.Spec.Prefix)
	} else if a.ko.Spec.Prefix != nil && b.ko.Spec.Prefix != nil {
		if *a.ko.Spec.Prefix != *b.ko.Spec.Prefix {
			delta.Add("Spec.Prefix", a.ko.Spec.Prefix, b.ko.Spec.Prefix)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RepositoryPolicy, b.ko.Spec.RepositoryPolicy) {
		delta.Add("Spec.RepositoryPolicy", a.ko.Spec.RepositoryPolicy, b.ko.Spec.RepositoryPolicy)
	} else if a.ko.Spec.RepositoryPolicy != nil && b.ko.Spec.RepositoryPolicy != nil {
		if *a.ko.Spec.RepositoryPolicy != *b.ko.Spec.RepositoryPolicy {
			delta.Add("Spec.RepositoryPolicy", a.ko.Spec.RepositoryPolicy, b.ko.Spec.RepositoryPolicy)
		}
	}
	if len(a.ko.Spec.ResourceTags) != len(b.ko.Spec.ResourceTags) {
		delta.Add("Spec.ResourceTags", a.ko.Spec.ResourceTags, b.ko.Spec.ResourceTags)
	} else if len(a.ko.Spec.ResourceTags) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ResourceTags, b.ko.Spec.ResourceTags) {
			delta.Add("Spec.ResourceTags", a.ko.Spec.ResourceTags, b.ko.Spec.ResourceTags)
		}
	}

	return delta
}
