// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package repository

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/ecr"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/ecr/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/ecr-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Repository{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeRepositoriesOutput
	resp, err = rm.sdkapi.DescribeRepositories(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeRepositories", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "RepositoryNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.Repositories {
		if elem.CreatedAt != nil {
			ko.Status.CreatedAt = &metav1.Time{*elem.CreatedAt}
		} else {
			ko.Status.CreatedAt = nil
		}
		if elem.EncryptionConfiguration != nil {
			f1 := &svcapitypes.EncryptionConfiguration{}
			if elem.EncryptionConfiguration.EncryptionType != "" {
				f1.EncryptionType = aws.String(string(elem.EncryptionConfiguration.EncryptionType))
			}
			if elem.EncryptionConfiguration.KmsKey != nil {
				f1.KMSKey = elem.EncryptionConfiguration.KmsKey
			}
			ko.Spec.EncryptionConfiguration = f1
		} else {
			ko.Spec.EncryptionConfiguration = nil
		}
		if elem.ImageScanningConfiguration != nil {
			f2 := &svcapitypes.ImageScanningConfiguration{}
			f2.ScanOnPush = &elem.ImageScanningConfiguration.ScanOnPush
			ko.Spec.ImageScanningConfiguration = f2
		} else {
			ko.Spec.ImageScanningConfiguration = nil
		}
		if elem.ImageTagMutability != "" {
			ko.Spec.ImageTagMutability = aws.String(string(elem.ImageTagMutability))
		} else {
			ko.Spec.ImageTagMutability = nil
		}
		if elem.ImageTagMutabilityExclusionFilters != nil {
			f4 := []*svcapitypes.ImageTagMutabilityExclusionFilter{}
			for _, f4iter := range elem.ImageTagMutabilityExclusionFilters {
				f4elem := &svcapitypes.ImageTagMutabilityExclusionFilter{}
				if f4iter.Filter != nil {
					f4elem.Filter = f4iter.Filter
				}
				if f4iter.FilterType != "" {
					f4elem.FilterType = aws.String(string(f4iter.FilterType))
				}
				f4 = append(f4, f4elem)
			}
			ko.Spec.ImageTagMutabilityExclusionFilters = f4
		} else {
			ko.Spec.ImageTagMutabilityExclusionFilters = nil
		}
		if elem.RegistryId != nil {
			ko.Spec.RegistryID = elem.RegistryId
		} else {
			ko.Spec.RegistryID = nil
		}
		if elem.RepositoryArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.RepositoryArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.RepositoryName != nil {
			if ko.Spec.Name != nil {
				if *elem.RepositoryName != *ko.Spec.Name {
					continue
				}
			}
			ko.Spec.Name = elem.RepositoryName
		} else {
			ko.Spec.Name = nil
		}
		if elem.RepositoryUri != nil {
			ko.Status.RepositoryURI = elem.RepositoryUri
		} else {
			ko.Status.RepositoryURI = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	if err := rm.setResourceAdditionalFields(ctx, ko); err != nil {
		return nil, err
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Spec.Name == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeRepositoriesInput, error) {
	res := &svcsdk.DescribeRepositoriesInput{}

	if r.ko.Spec.RegistryID != nil {
		res.RegistryId = r.ko.Spec.RegistryID
	}
	if r.ko.Spec.Name != nil {
		f3 := []string{}
		f3 = append(f3, *r.ko.Spec.Name)
		res.RepositoryNames = f3
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateRepositoryOutput
	_ = resp
	resp, err = rm.sdkapi.CreateRepository(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateRepository", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.Repository.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Repository.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Repository.EncryptionConfiguration != nil {
		f1 := &svcapitypes.EncryptionConfiguration{}
		if resp.Repository.EncryptionConfiguration.EncryptionType != "" {
			f1.EncryptionType = aws.String(string(resp.Repository.EncryptionConfiguration.EncryptionType))
		}
		if resp.Repository.EncryptionConfiguration.KmsKey != nil {
			f1.KMSKey = resp.Repository.EncryptionConfiguration.KmsKey
		}
		ko.Spec.EncryptionConfiguration = f1
	} else {
		ko.Spec.EncryptionConfiguration = nil
	}
	if resp.Repository.ImageScanningConfiguration != nil {
		f2 := &svcapitypes.ImageScanningConfiguration{}
		f2.ScanOnPush = &resp.Repository.ImageScanningConfiguration.ScanOnPush
		ko.Spec.ImageScanningConfiguration = f2
	} else {
		ko.Spec.ImageScanningConfiguration = nil
	}
	if resp.Repository.ImageTagMutability != "" {
		ko.Spec.ImageTagMutability = aws.String(string(resp.Repository.ImageTagMutability))
	} else {
		ko.Spec.ImageTagMutability = nil
	}
	if resp.Repository.ImageTagMutabilityExclusionFilters != nil {
		f4 := []*svcapitypes.ImageTagMutabilityExclusionFilter{}
		for _, f4iter := range resp.Repository.ImageTagMutabilityExclusionFilters {
			f4elem := &svcapitypes.ImageTagMutabilityExclusionFilter{}
			if f4iter.Filter != nil {
				f4elem.Filter = f4iter.Filter
			}
			if f4iter.FilterType != "" {
				f4elem.FilterType = aws.String(string(f4iter.FilterType))
			}
			f4 = append(f4, f4elem)
		}
		ko.Spec.ImageTagMutabilityExclusionFilters = f4
	} else {
		ko.Spec.ImageTagMutabilityExclusionFilters = nil
	}
	if resp.Repository.RegistryId != nil {
		ko.Spec.RegistryID = resp.Repository.RegistryId
	} else {
		ko.Spec.RegistryID = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Repository.RepositoryArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Repository.RepositoryArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Repository.RepositoryName != nil {
		ko.Spec.Name = resp.Repository.RepositoryName
	} else {
		ko.Spec.Name = nil
	}
	if resp.Repository.RepositoryUri != nil {
		ko.Status.RepositoryURI = resp.Repository.RepositoryUri
	} else {
		ko.Status.RepositoryURI = nil
	}

	rm.setStatusDefaults(ko)
	// Repository policy and lifecycle policy need to be set after creation.
	// Return a requeue error to trigger another reconcile loop where these
	// will be handled by the update path, avoiding the issue where a failure
	// in these API calls would leave the repository unmanaged.
	if (ko.Spec.Policy != nil && *ko.Spec.Policy != "") ||
		(ko.Spec.LifecyclePolicy != nil && *ko.Spec.LifecyclePolicy != "") {
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, aws.String("repository created, requeue for updates"), nil)
	}
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateRepositoryInput, error) {
	res := &svcsdk.CreateRepositoryInput{}

	if r.ko.Spec.EncryptionConfiguration != nil {
		f0 := &svcsdktypes.EncryptionConfiguration{}
		if r.ko.Spec.EncryptionConfiguration.EncryptionType != nil {
			f0.EncryptionType = svcsdktypes.EncryptionType(*r.ko.Spec.EncryptionConfiguration.EncryptionType)
		}
		if r.ko.Spec.EncryptionConfiguration.KMSKey != nil {
			f0.KmsKey = r.ko.Spec.EncryptionConfiguration.KMSKey
		}
		res.EncryptionConfiguration = f0
	}
	if r.ko.Spec.ImageScanningConfiguration != nil {
		f1 := &svcsdktypes.ImageScanningConfiguration{}
		if r.ko.Spec.ImageScanningConfiguration.ScanOnPush != nil {
			f1.ScanOnPush = *r.ko.Spec.ImageScanningConfiguration.ScanOnPush
		}
		res.ImageScanningConfiguration = f1
	}
	if r.ko.Spec.ImageTagMutability != nil {
		res.ImageTagMutability = svcsdktypes.ImageTagMutability(*r.ko.Spec.ImageTagMutability)
	}
	if r.ko.Spec.ImageTagMutabilityExclusionFilters != nil {
		f3 := []svcsdktypes.ImageTagMutabilityExclusionFilter{}
		for _, f3iter := range r.ko.Spec.ImageTagMutabilityExclusionFilters {
			f3elem := &svcsdktypes.ImageTagMutabilityExclusionFilter{}
			if f3iter.Filter != nil {
				f3elem.Filter = f3iter.Filter
			}
			if f3iter.FilterType != nil {
				f3elem.FilterType = svcsdktypes.ImageTagMutabilityExclusionFilterType(*f3iter.FilterType)
			}
			f3 = append(f3, *f3elem)
		}
		res.ImageTagMutabilityExclusionFilters = f3
	}
	if r.ko.Spec.RegistryID != nil {
		res.RegistryId = r.ko.Spec.RegistryID
	}
	if r.ko.Spec.Name != nil {
		res.RepositoryName = r.ko.Spec.Name
	}
	if r.ko.Spec.Tags != nil {
		f6 := []svcsdktypes.Tag{}
		for _, f6iter := range r.ko.Spec.Tags {
			f6elem := &svcsdktypes.Tag{}
			if f6iter.Key != nil {
				f6elem.Key = f6iter.Key
			}
			if f6iter.Value != nil {
				f6elem.Value = f6iter.Value
			}
			f6 = append(f6, *f6elem)
		}
		res.Tags = f6
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateRepository(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	input.Force = GetDeleteForce(&r.ko.ObjectMeta)
	var resp *svcsdk.DeleteRepositoryOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteRepository(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteRepository", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteRepositoryInput, error) {
	res := &svcsdk.DeleteRepositoryInput{}

	if r.ko.Spec.RegistryID != nil {
		res.RegistryId = r.ko.Spec.RegistryID
	}
	if r.ko.Spec.Name != nil {
		res.RepositoryName = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Repository,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
