// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RepositoryCreationTemplateSpec defines the desired state of RepositoryCreationTemplate.
//
// An object representing the repository creation template for automatic repository creation on image push.
type RepositoryCreationTemplateSpec struct {

	// The repository name prefix where the template applies.
	//
	// Required: true
	// Regex Pattern: `^[a-zA-Z0-9-_]+$`
	RepositoryNamePrefix *string `json:"repositoryNamePrefix"`

	// The encryption configuration to apply to repositories created by this template.
	// +kubebuilder:validation:Optional
	EncryptionConfiguration *RepositoryEncryptionConfiguration `json:"encryptionConfiguration,omitempty"`

	// The image tag mutability setting for repositories created by this template.
	// +kubebuilder:validation:Optional
	ImageTagMutability *string `json:"imageTagMutability,omitempty"`

	// The image scanning configuration for repositories created by this template.
	// +kubebuilder:validation:Optional
	ImageScanningConfiguration *ImageScanningConfiguration `json:"imageScanningConfiguration,omitempty"`

	// The resource tags to apply to repositories created by this template.
	// +kubebuilder:validation:Optional
	ResourceTags []*Tag `json:"resourceTags,omitempty"`

	// The description of the template.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty"`
}

// RepositoryCreationTemplateStatus defines the observed state of RepositoryCreationTemplate
type RepositoryCreationTemplateStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The ARN of the repository creation template
	// +kubebuilder:validation:Optional
	RepositoryCreationTemplateARN *string `json:"repositoryCreationTemplateARN,omitempty"`
	// The date and time when the template was created
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The date and time when the template was last updated
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// RepositoryCreationTemplate is the Schema for the RepositoryCreationTemplates API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="PREFIX",type=string,priority=0,JSONPath=`.spec.repositoryNamePrefix`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
type RepositoryCreationTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RepositoryCreationTemplateSpec   `json:"spec,omitempty"`
	Status            RepositoryCreationTemplateStatus `json:"status,omitempty"`
}

// RepositoryCreationTemplateList contains a list of RepositoryCreationTemplate
// +kubebuilder:object:root=true
type RepositoryCreationTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepositoryCreationTemplate `json:"items"`
}

func init() {
	SchemeBuilder.Register(&RepositoryCreationTemplate{}, &RepositoryCreationTemplateList{})
}
