// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RepositoryCreationTemplateSpec defines the desired state of RepositoryCreationTemplate.
//
// The details of the repository creation template associated with the request.
type RepositoryCreationTemplateSpec struct {

	// A list of enumerable strings representing the Amazon ECR repository creation
	// scenarios that this template will apply towards. The two supported scenarios
	// are PULL_THROUGH_CACHE and REPLICATION
	// +kubebuilder:validation:Required
	AppliedFor []*string `json:"appliedFor"`
	// The ARN of the role to be assumed by Amazon ECR. This role must be in the
	// same account as the registry that you are configuring. Amazon ECR will assume
	// your supplied role when the customRoleArn is specified. When this field isn't
	// specified, Amazon ECR will use the service-linked role for the repository
	// creation template.
	CustomRoleARN *string                                  `json:"customRoleARN,omitempty"`
	CustomRoleRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"customRoleRef,omitempty"`
	// A description for the repository creation template.
	Description *string `json:"description,omitempty"`
	// The encryption configuration to use for repositories created using the template.
	EncryptionConfiguration *EncryptionConfigurationForRepositoryCreationTemplate `json:"encryptionConfiguration,omitempty"`
	// The tag mutability setting for the repository. If this parameter is omitted,
	// the default setting of MUTABLE will be used which will allow image tags to
	// be overwritten. If IMMUTABLE is specified, all image tags within the repository
	// will be immutable which will prevent them from being overwritten.
	ImageTagMutability *string `json:"imageTagMutability,omitempty"`
	// A list of filters that specify which image tags should be excluded from the
	// repository creation template's image tag mutability setting.
	ImageTagMutabilityExclusionFilters []*ImageTagMutabilityExclusionFilter `json:"imageTagMutabilityExclusionFilters,omitempty"`
	// The lifecycle policy to use for repositories created using the template.
	LifecyclePolicy *string `json:"lifecyclePolicy,omitempty"`
	// The repository namespace prefix to associate with the template. All repositories
	// created using this namespace prefix will have the settings defined in this
	// template applied. For example, a prefix of prod would apply to all repositories
	// beginning with prod/. Similarly, a prefix of prod/team would apply to all
	// repositories beginning with prod/team/.
	//
	// To apply a template to all repositories in your registry that don't have
	// an associated creation template, you can use ROOT as the prefix.
	//
	// There is always an assumed / applied to the end of the prefix. If you specify
	// ecr-public as the prefix, Amazon ECR treats that as ecr-public/. When using
	// a pull through cache rule, the repository prefix you specify during rule
	// creation is what you should specify as your repository creation template
	// prefix as well.
	//
	// Regex Pattern: `^((?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*/?|ROOT)$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Prefix *string `json:"prefix"`
	// The repository policy to apply to repositories created using the template.
	// A repository policy is a permissions policy associated with a repository
	// to control access permissions.
	RepositoryPolicy *string `json:"repositoryPolicy,omitempty"`
	// The metadata to apply to the repository to help you categorize and organize.
	// Each tag consists of a key and an optional value, both of which you define.
	// Tag keys can have a maximum character length of 128 characters, and tag values
	// can have a maximum length of 256 characters.
	ResourceTags []*Tag `json:"resourceTags,omitempty"`
}

// RepositoryCreationTemplateStatus defines the observed state of RepositoryCreationTemplate
type RepositoryCreationTemplateStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date and time, in JavaScript date format, when the repository creation
	// template was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The date and time, in JavaScript date format, when the repository creation
	// template was last updated.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// RepositoryCreationTemplate is the Schema for the RepositoryCreationTemplates API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type RepositoryCreationTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RepositoryCreationTemplateSpec   `json:"spec,omitempty"`
	Status            RepositoryCreationTemplateStatus `json:"status,omitempty"`
}

// RepositoryCreationTemplateList contains a list of RepositoryCreationTemplate
// +kubebuilder:object:root=true
type RepositoryCreationTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepositoryCreationTemplate `json:"items"`
}

func init() {
	SchemeBuilder.Register(&RepositoryCreationTemplate{}, &RepositoryCreationTemplateList{})
}
