// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// The image details of the Amazon ECR container image.
type AWSECRContainerImageDetails struct {
	Registry       *string `json:"registry,omitempty"`
	RepositoryName *string `json:"repositoryName,omitempty"`
}

// The encryption configuration for the repository. This determines how the
// contents of your repository are encrypted at rest.
//
// By default, when no encryption configuration is set or the AES256 encryption
// type is used, Amazon ECR uses server-side encryption with Amazon S3-managed
// encryption keys which encrypts your data at rest using an AES256 encryption
// algorithm. This does not require any action on your part.
//
// For more control over the encryption of the contents of your repository,
// you can use server-side encryption with Key Management Service key stored
// in Key Management Service (KMS) to encrypt your images. For more information,
// see Amazon ECR encryption at rest (https://docs.aws.amazon.com/AmazonECR/latest/userguide/encryption-at-rest.html)
// in the Amazon Elastic Container Registry User Guide.
type EncryptionConfiguration struct {
	EncryptionType *string `json:"encryptionType,omitempty"`
	KMSKey         *string `json:"kmsKey,omitempty"`
}

// The encryption configuration to associate with the repository creation template.
type EncryptionConfigurationForRepositoryCreationTemplate struct {
	EncryptionType *string `json:"encryptionType,omitempty"`
}

// The details of an enhanced image scan. This is returned when enhanced scanning
// is enabled for your private registry.
type EnhancedImageScanFinding struct {
	AWSAccountID *string `json:"awsAccountID,omitempty"`
}

// An object representing an Amazon ECR image.
type Image struct {
	RegistryID     *string `json:"registryID,omitempty"`
	RepositoryName *string `json:"repositoryName,omitempty"`
}

// An object that describes an image returned by a DescribeImages operation.
type ImageDetail struct {
	RegistryID     *string `json:"registryID,omitempty"`
	RepositoryName *string `json:"repositoryName,omitempty"`
}

// The status of the replication process for an image.
type ImageReplicationStatus struct {
	RegistryID *string `json:"registryID,omitempty"`
}

// Contains information about an image scan finding.
type ImageScanFinding struct {
	URI *string `json:"uri,omitempty"`
}

// The image scanning configuration for a repository.
type ImageScanningConfiguration struct {
	ScanOnPush *bool `json:"scanOnPush,omitempty"`
}

// Information about a package vulnerability finding.
type PackageVulnerabilityDetails struct {
	SourceURL *string `json:"sourceURL,omitempty"`
}

// The details of a pull through cache rule.
type PullThroughCacheRule_SDK struct {
	CreatedAt           *metav1.Time `json:"createdAt,omitempty"`
	CredentialARN       *string      `json:"credentialARN,omitempty"`
	ECRRepositoryPrefix *string      `json:"ecrRepositoryPrefix,omitempty"`
	RegistryID          *string      `json:"registryID,omitempty"`
	UpdatedAt           *metav1.Time `json:"updatedAt,omitempty"`
	UpstreamRegistry    *string      `json:"upstreamRegistry,omitempty"`
	UpstreamRegistryURL *string      `json:"upstreamRegistryURL,omitempty"`
}

// Details about the recommended course of action to remediate the finding.
type Recommendation struct {
	URL *string `json:"url,omitempty"`
}

// An array of objects representing the destination for a replication rule.
type ReplicationDestination struct {
	RegistryID *string `json:"registryID,omitempty"`
}

// The details of the repository creation template associated with the request.
type RepositoryCreationTemplate struct {
	ImageTagMutability *string `json:"imageTagMutability,omitempty"`
	RepositoryPolicy   *string `json:"repositoryPolicy,omitempty"`
	ResourceTags       []*Tag  `json:"resourceTags,omitempty"`
}

// The details of the scanning configuration for a repository.
type RepositoryScanningConfiguration struct {
	RepositoryARN  *string `json:"repositoryARN,omitempty"`
	RepositoryName *string `json:"repositoryName,omitempty"`
	ScanOnPush     *bool   `json:"scanOnPush,omitempty"`
}

// The details about any failures associated with the scanning configuration
// of a repository.
type RepositoryScanningConfigurationFailure struct {
	RepositoryName *string `json:"repositoryName,omitempty"`
}

// An object representing a repository.
type Repository_SDK struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The encryption configuration for the repository. This determines how the
	// contents of your repository are encrypted at rest.
	//
	// By default, when no encryption configuration is set or the AES256 encryption
	// type is used, Amazon ECR uses server-side encryption with Amazon S3-managed
	// encryption keys which encrypts your data at rest using an AES256 encryption
	// algorithm. This does not require any action on your part.
	//
	// For more control over the encryption of the contents of your repository,
	// you can use server-side encryption with Key Management Service key stored
	// in Key Management Service (KMS) to encrypt your images. For more information,
	// see Amazon ECR encryption at rest (https://docs.aws.amazon.com/AmazonECR/latest/userguide/encryption-at-rest.html)
	// in the Amazon Elastic Container Registry User Guide.
	EncryptionConfiguration *EncryptionConfiguration `json:"encryptionConfiguration,omitempty"`
	// The image scanning configuration for a repository.
	ImageScanningConfiguration *ImageScanningConfiguration `json:"imageScanningConfiguration,omitempty"`
	ImageTagMutability         *string                     `json:"imageTagMutability,omitempty"`
	RegistryID                 *string                     `json:"registryID,omitempty"`
	RepositoryARN              *string                     `json:"repositoryARN,omitempty"`
	RepositoryName             *string                     `json:"repositoryName,omitempty"`
	RepositoryURI              *string                     `json:"repositoryURI,omitempty"`
}

// The metadata to apply to a resource to help you categorize and organize them.
// Each tag consists of a key and a value, both of which you define. Tag keys
// can have a maximum character length of 128 characters, and tag values can
// have a maximum length of 256 characters.
type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}
