// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package pull_through_cache_rule

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.CustomRoleARN, b.ko.Spec.CustomRoleARN) {
		delta.Add("Spec.CustomRoleARN", a.ko.Spec.CustomRoleARN, b.ko.Spec.CustomRoleARN)
	} else if a.ko.Spec.CustomRoleARN != nil && b.ko.Spec.CustomRoleARN != nil {
		if *a.ko.Spec.CustomRoleARN != *b.ko.Spec.CustomRoleARN {
			delta.Add("Spec.CustomRoleARN", a.ko.Spec.CustomRoleARN, b.ko.Spec.CustomRoleARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ECRRepositoryPrefix, b.ko.Spec.ECRRepositoryPrefix) {
		delta.Add("Spec.ECRRepositoryPrefix", a.ko.Spec.ECRRepositoryPrefix, b.ko.Spec.ECRRepositoryPrefix)
	} else if a.ko.Spec.ECRRepositoryPrefix != nil && b.ko.Spec.ECRRepositoryPrefix != nil {
		if *a.ko.Spec.ECRRepositoryPrefix != *b.ko.Spec.ECRRepositoryPrefix {
			delta.Add("Spec.ECRRepositoryPrefix", a.ko.Spec.ECRRepositoryPrefix, b.ko.Spec.ECRRepositoryPrefix)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RegistryID, b.ko.Spec.RegistryID) {
		delta.Add("Spec.RegistryID", a.ko.Spec.RegistryID, b.ko.Spec.RegistryID)
	} else if a.ko.Spec.RegistryID != nil && b.ko.Spec.RegistryID != nil {
		if *a.ko.Spec.RegistryID != *b.ko.Spec.RegistryID {
			delta.Add("Spec.RegistryID", a.ko.Spec.RegistryID, b.ko.Spec.RegistryID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.UpstreamRegistryURL, b.ko.Spec.UpstreamRegistryURL) {
		delta.Add("Spec.UpstreamRegistryURL", a.ko.Spec.UpstreamRegistryURL, b.ko.Spec.UpstreamRegistryURL)
	} else if a.ko.Spec.UpstreamRegistryURL != nil && b.ko.Spec.UpstreamRegistryURL != nil {
		if *a.ko.Spec.UpstreamRegistryURL != *b.ko.Spec.UpstreamRegistryURL {
			delta.Add("Spec.UpstreamRegistryURL", a.ko.Spec.UpstreamRegistryURL, b.ko.Spec.UpstreamRegistryURL)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.UpstreamRepositoryPrefix, b.ko.Spec.UpstreamRepositoryPrefix) {
		delta.Add("Spec.UpstreamRepositoryPrefix", a.ko.Spec.UpstreamRepositoryPrefix, b.ko.Spec.UpstreamRepositoryPrefix)
	} else if a.ko.Spec.UpstreamRepositoryPrefix != nil && b.ko.Spec.UpstreamRepositoryPrefix != nil {
		if *a.ko.Spec.UpstreamRepositoryPrefix != *b.ko.Spec.UpstreamRepositoryPrefix {
			delta.Add("Spec.UpstreamRepositoryPrefix", a.ko.Spec.UpstreamRepositoryPrefix, b.ko.Spec.UpstreamRepositoryPrefix)
		}
	}

	return delta
}
